{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Machine Learning Model ANN with Grid Search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 150,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler,LabelEncoder\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from scikeras.wrappers import KerasClassifier\n",
    "from keras import optimizers\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "sns.set(rc={'figure.figsize':(15,10)})\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 151,
   "metadata": {},
   "outputs": [],
   "source": [
    "def position_index(x):\n",
    "    if x<4:\n",
    "        return 1\n",
    "    if x>10:\n",
    "        return 3\n",
    "    else :\n",
    "        return 2"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Prepare data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 152,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_train = pd.read_csv('./data_f1/ANNData/cleaned_data.csv')\n",
    "x_test = pd.read_csv('./data_f1/ANNData/cleaned_data_2022.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 153,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_train = x_train[['GP_name','quali_pos','constructor','driver','position','driver_confidence','constructor_reliability','active_driver','active_constructor']]\n",
    "x_test = x_test[['GP_name','quali_pos','constructor','driver','position','driver_confidence','constructor_reliability','active_driver','active_constructor']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_train = x_train[x_train['active_constructor']==1]\n",
    "x_train = x_train[x_train['active_driver']==1]\n",
    "\n",
    "x_test = x_test[x_test['active_constructor']==1]\n",
    "x_test = x_test[x_test['active_driver']==1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 155,
   "metadata": {},
   "outputs": [],
   "source": [
    "sc  = StandardScaler()\n",
    "le = LabelEncoder()\n",
    "\n",
    "x_train['GP_name'] = le.fit_transform(x_train['GP_name'])\n",
    "x_train['constructor'] = le.fit_transform(x_train['constructor'])\n",
    "x_train['driver'] = le.fit_transform(x_train['driver'])\n",
    "x_train['GP_name'] = le.fit_transform(x_train['GP_name'])\n",
    "X_train = x_train.drop(['position','active_driver','active_constructor'],axis=1)\n",
    "y_train = x_train['position'].apply(lambda x: position_index(x))\n",
    "\n",
    "x_test['GP_name'] = le.fit_transform(x_test['GP_name'])\n",
    "x_test['constructor'] = le.fit_transform(x_test['constructor'])\n",
    "x_test['driver'] = le.fit_transform(x_test['driver'])\n",
    "x_test['GP_name'] = le.fit_transform(x_test['GP_name'])\n",
    "X_test = x_test.drop(['position','active_driver','active_constructor'],axis=1)\n",
    "y_test = x_test['position'].apply(lambda x: position_index(x))"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Hyperparameter tuning with GridSearch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 156,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to create model, required for KerasClassifier\n",
    "def create_model(optimizer='adam', activation='relu', neurons=32):\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(neurons, activation=activation, input_shape=(6,)))\n",
    "    model.add(Dense(4, activation='softmax'))\n",
    "    # Compile model\n",
    "    # opt = optimizers.Adamax(learning_rate=0.01)\n",
    "    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 157,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = KerasClassifier(model=create_model, verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 158,
   "metadata": {},
   "outputs": [],
   "source": [
    "# https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/\n",
    "\n",
    "batch_size = [32, 64, 128]\n",
    "epochs = [10, 25, 50]\n",
    "optimizer = ['Adam', 'Adamax', 'Nadam']\n",
    "learn_rate = [0.001, 0.01, 0.1]\n",
    "momentum = [0.0, 0.2, 0.4]\n",
    "activation = ['relu', 'tanh', 'sigmoid']\n",
    "neurons = [16, 32, 64]\n",
    "\n",
    "param_grid = dict(\n",
    "                 batch_size=batch_size, \n",
    "                 epochs=epochs, \n",
    "                 optimizer__learning_rate=learn_rate, \n",
    "                 optimizer__momentum=momentum, \n",
    "                 model__optimizer=optimizer, \n",
    "                 model__activation=activation,\n",
    "                 model__neurons=neurons\n",
    "                 )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 159,
   "metadata": {},
   "outputs": [],
   "source": [
    "grid_search = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 160,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:18:37.528620: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:20:09.483879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:20:23.033069: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:20:31.326895: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:20:37.572885: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:20:56.386386: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:20:58.159932: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:20:58.788587: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:21:06.889772: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 444, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1114, in score\n",
      "    y_pred = self.predict(X)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1054, in predict\n",
      "    y_pred = self.target_encoder_.inverse_transform(y_pred)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/scikeras/utils/transformers.py\", line 265, in inverse_transform\n",
      "    class_predictions = self._final_encoder.inverse_transform(class_predictions)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/pipeline.py\", line 686, in inverse_transform\n",
      "    Xt = transform.inverse_transform(Xt)\n",
      "  File \"/home/sdp/miniconda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1442, in inverse_transform\n",
      "    X_tr[:, i] = self.categories_[i][labels.astype(\"int64\", copy=False)]\n",
      "IndexError: index 3 is out of bounds for axis 0 with size 3\n",
      "\n",
      "  warnings.warn(\n",
      "2023-06-03 16:21:28.354750: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:21:39.637269: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:21:48.554970: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:22:21.892164: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:22:25.973532: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:22:53.335064: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:23:02.739752: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:23:12.083991: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:23:25.762573: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2023-06-03 16:23:44.252971: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"
     ]
    }
   ],
   "source": [
    "# Fit the grid search object to the training data\n",
    "grid_result = grid_search.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 161,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best hyperparameters: {'batch_size': 32, 'epochs': 50, 'model__activation': 'tanh', 'model__neurons': 64, 'model__optimizer': 'Nadam', 'optimizer__learning_rate': 0.01, 'optimizer__momentum': 0.0}\n",
      "Best score: 0.9438826095578029\n"
     ]
    }
   ],
   "source": [
    "# Print the best hyperparameters and the best score\n",
    "print(\"Best hyperparameters:\", grid_result.best_params_)\n",
    "print(\"Best score:\", grid_result.best_score_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 162,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-8 {color: black;background-color: white;}#sk-container-id-8 pre{padding: 0;}#sk-container-id-8 div.sk-toggleable {background-color: white;}#sk-container-id-8 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-8 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-8 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-8 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-8 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-8 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-8 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-8 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-8 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-8 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-8 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-8 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-8 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-8 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-8 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-8 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-8 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-8 div.sk-item {position: relative;z-index: 1;}#sk-container-id-8 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-8 div.sk-item::before, #sk-container-id-8 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-8 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-8 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-8 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-8 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-8 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-8 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-8 div.sk-label-container {text-align: center;}#sk-container-id-8 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-8 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-8\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>KerasClassifier(\n",
       "\tmodel=&lt;function create_model at 0x7f1dac908310&gt;\n",
       "\tbuild_fn=None\n",
       "\twarm_start=False\n",
       "\trandom_state=None\n",
       "\toptimizer=rmsprop\n",
       "\tloss=None\n",
       "\tmetrics=None\n",
       "\tbatch_size=32\n",
       "\tvalidation_batch_size=None\n",
       "\tverbose=0\n",
       "\tcallbacks=None\n",
       "\tvalidation_split=0.0\n",
       "\tshuffle=True\n",
       "\trun_eagerly=False\n",
       "\tepochs=50\n",
       "\tmodel__activation=tanh\n",
       "\tmodel__neurons=64\n",
       "\tmodel__optimizer=Nadam\n",
       "\toptimizer__learning_rate=0.01\n",
       "\toptimizer__momentum=0.0\n",
       "\tclass_weight=None\n",
       ")</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-8\" type=\"checkbox\" checked><label for=\"sk-estimator-id-8\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">KerasClassifier</label><div class=\"sk-toggleable__content\"><pre>KerasClassifier(\n",
       "\tmodel=&lt;function create_model at 0x7f1dac908310&gt;\n",
       "\tbuild_fn=None\n",
       "\twarm_start=False\n",
       "\trandom_state=None\n",
       "\toptimizer=rmsprop\n",
       "\tloss=None\n",
       "\tmetrics=None\n",
       "\tbatch_size=32\n",
       "\tvalidation_batch_size=None\n",
       "\tverbose=0\n",
       "\tcallbacks=None\n",
       "\tvalidation_split=0.0\n",
       "\tshuffle=True\n",
       "\trun_eagerly=False\n",
       "\tepochs=50\n",
       "\tmodel__activation=tanh\n",
       "\tmodel__neurons=64\n",
       "\tmodel__optimizer=Nadam\n",
       "\toptimizer__learning_rate=0.01\n",
       "\toptimizer__momentum=0.0\n",
       "\tclass_weight=None\n",
       ")</pre></div></div></div></div></div>"
      ],
      "text/plain": [
       "KerasClassifier(\n",
       "\tmodel=<function create_model at 0x7f1dac908310>\n",
       "\tbuild_fn=None\n",
       "\twarm_start=False\n",
       "\trandom_state=None\n",
       "\toptimizer=rmsprop\n",
       "\tloss=None\n",
       "\tmetrics=None\n",
       "\tbatch_size=32\n",
       "\tvalidation_batch_size=None\n",
       "\tverbose=0\n",
       "\tcallbacks=None\n",
       "\tvalidation_split=0.0\n",
       "\tshuffle=True\n",
       "\trun_eagerly=False\n",
       "\tepochs=50\n",
       "\tmodel__activation=tanh\n",
       "\tmodel__neurons=64\n",
       "\tmodel__optimizer=Nadam\n",
       "\toptimizer__learning_rate=0.01\n",
       "\toptimizer__momentum=0.0\n",
       "\tclass_weight=None\n",
       ")"
      ]
     },
     "execution_count": 162,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Re-train the model with the best hyperparameters\n",
    "best_clf = grid_search.best_estimator_\n",
    "best_clf.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 163,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Misclassified examples: 64\n"
     ]
    }
   ],
   "source": [
    "y_pred = best_clf.predict(X_test)\n",
    "print('Misclassified examples: %d' % (y_test != y_pred).sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 164,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Testing accuracy: 0.8545454545454545\n"
     ]
    }
   ],
   "source": [
    " # Test the model with the best hyperparameters on the testing data\n",
    "accuracy = best_clf.score(X_test, y_test)\n",
    "print(\"Testing accuracy:\", accuracy)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 165,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAABHQAAANlCAYAAAAdIa4GAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAABnMklEQVR4nO3debid47k/8O/OKHMEMUVEkIiDRFtCRZVEtRHUwXG0lFKlrRparWhRTnuKamsIVY0YaiaGEokpJQgVVEOMiSHElBBJRBIZ9vr94Zd9umW2l7XyJp/PdeU6We/7rPe9d5zT03zd9/PUlEqlUgAAAAAojEbVLgAAAACAFSPQAQAAACgYgQ4AAABAwQh0AAAAAApGoAMAAABQMAIdAAAAgIIR6AAAAAAUjEAHAAAAoGAEOgAAAAAFI9ABgAp47bXXcsIJJ2SnnXZKjx490r179wwcOLDidUyaNCndu3dP9+7dK/5u/s8hhxyS7t2755Zbbql2KQBAQTWpdgEA8FnMnDkzQ4cOzYMPPpgJEybkgw8+SJMmTbLuuuumV69e2XPPPdOnT5/U1NRUu9RMmzYt3/72t/Pee++lpqYm7dq1S5MmTdK6detql7bSGzRoUC688MK6z/fdd1822mijJa4fOnRofvnLX9Z9vuaaa/KlL32pbLUkyaGHHpq2bduW5ZkAAJ+VQAeAwhkxYkROP/30TJs2re5a69ats2DBgrz66qt59dVXc+utt2arrbbKRRddlPXWW696xSa58847895776VLly656qqr0rFjx6rV0rRp02yyySZVe39D/e1vf8sxxxyz1Pufl4XB0r777tvgQGf99dfPJptskjZt2pSjNABgNSTQAaBQbrjhhvzqV79KqVRKt27d8oMf/CA777xz3V+M33vvvdx///257LLLMm7cuEycOLHqgc748eOTJLvttltVw5wkWXfddXPXXXdVtYbPYoMNNshbb72VO+64Y4mBzltvvZXHH3+8bu3K7He/+121SwAACs4eOgAUxrPPPptf//rXKZVK2X333XPzzTenf//+9boc1l577RxwwAEZNmxYfvjDH6ZRo+r/v7qPP/44SdKyZcsqV1JcG2+8cbbaaqu89tprefrppxe75o477kipVMpee+1V4eoAACqv+v8tFwCW03nnnZd58+Zlgw02yNlnn51mzZotcW3jxo1z3HHHLXb/lFdffTW/+MUvsuuuu2arrbZK7969c/jhh2fEiBFLfN7CjYQnTZqUN954IwMHDkyfPn2y9dZb52tf+1ouuOCCuuBmoYEDB9bb+PbCCy+se86/b0q8PBvk/vv7P+2ee+7JEUcckR133DH/8R//kd69e6d///45+eST8+CDD9ZbuzybIj/88MM5+uijs+OOO2arrbbKzjvvnJ/85CcZN27cYtc/9thj6d69e3bbbbckyZgxY3LEEUdk++23T8+ePbPffvvltttuW+L7ltc+++yTJLn99tsXe3/h9b333nuJz1iwYEEeeOCB/PKXv8w3v/nN9O7dO1tttVV23XXX/PznP8+LL764yHcGDRpU78+rb9++9f45/vvm1gv/mQ8aNChz5szJhRdemD333DM9e/as97+Li/tnPnPmzLpn//rXv15s/Y8++mi22GKLbLHFFvnHP/6xxJ8TAFj1CXQAKIS33367Lpw45JBD0qpVq+X63qc3Rb7vvvuy99575+abb85bb72VFi1aZObMmRk9enSOP/74nHTSSamtrV3i855//vnst99+ufXWWzN79uzMnz8/EydOzEUXXZRjjz223trWrVtn7bXXTvPmzZN80qGz9tpr1/0qh9///vf58Y9/nIcffjhTp05NixYt8tFHH+Xll1/OLbfcUm9D4eVxzjnn5Igjjsj999+fadOmpUWLFpkyZUruvPPOHHDAAbn++uuX+v2bbrophx56aEaPHp3a2trMmTMn48aNy0knnZQhQ4Y05EfNnnvumSZNmmT48OGZP39+vXvPPvtsJkyYkC233DKbbbbZEp/x8ssv56ijjsrQoUPzwgsvpLa2No0aNcpbb72Vv/3tb9l///3z97//vd53Fv5zW2jNNdes989xcZtbz5kzJ9/61rcyaNCgTJw4MU2aLHvKvXXr1jnrrLPSqFGjXHPNNXnkkUfq3f/www9z8sknp1Qq5ZBDDskOO+ywzGcCAKsugQ4AhTBmzJi633/1q1/9TM+YOHFiTjzxxMydOzd9+vTJfffdl8cffzxPPPFETjzxxDRq1Ci33XZbLrvssiU+4xe/+EW23nrrjBgxIk8++WT++c9/5uc//3lqamrywAMP5P77769be8opp2T06NHp379/kuTwww/P6NGj63411BtvvJFLL700jRs3zsknn5wnn3wyTzzxRJ555pk89NBDOeuss/LFL35xuZ93xx135NJLL02SHHHEEXnsscfy+OOP58EHH8yAAQNSW1ubM844I//6178W+/2pU6fmjDPOyKGHHppHHnkkTzzxRB599NHsueeeST7psJo6depn/nnXWmut7LTTTnn//fcX+fNbuBny0rpzkk82hT7ggANyxRVX5J///Gcef/zxjB07Nvfee2/+8z//M3Pnzs3AgQMzc+bMuu8cccQR9d43dOjQev8cTznllEXec+211+bNN9/MBRdckH/961958sknc/PNNy/zZ9xuu+1y2GGHpVQq5eSTT86HH35Yd+/Xv/513n777XTt2jUnnnjiMp8FAKzaBDoAFMIrr7ySJGnWrNlnPqXpz3/+c2bPnp3NN988F198cd3x1y1atMiRRx6Z7373u0mSSy65JLNnz17sM9q2bZuLL744Xbt2rfvuEUccUTdudPfdd3+m2j6LZ555JqVSKV/+8pdz2GGH1XWK1NTUpGPHjtl3331z0kknLdezSqVSzj///CTJAQcckJ///Od1Jzl17Ngx55xzTnr27Jna2tq647s/bfbs2fn617+egQMHpkOHDkmSDh065Kyzzsraa6+duXPn5oEHHmjQz7y4sasFCxbkzjvvTOPGjTNgwIClfn+TTTbJb37zm+y44451exrV1NSkc+fOOfPMM9OnT59Mnz59qeN3y2PWrFk577zzsscee9R152y88cbL9d0TTjghm2++ed5555260at77rknf/vb39KkSZOcffbZdV1fAMDqS6ADQCEsPKK8Xbt2i4xRLY9SqZR77703yScdF4vbf+fwww9Ps2bNMmPGjDz66KOLfc73vve9xX531113TfJ/J1pVwsIAZ+rUqUsdE1sezz33XN54440kydFHH73I/UaNGuX73/9+kmT06NH1Okf+3Q9+8INFrjVr1ixf/vKXkzT8z6dv375p1apVRo4cmY8++qiunvfeey877rhj1llnnQY9f+edd06SjB07tkHP2WKLLbLjjjt+pu82a9Ys55xzTpo2bZq//e1vufbaa3PaaaclSY466qhss802DaoNAFg1CHQAWC28/vrrdSFE7969F7tm7bXXrtt/5bnnnlvsmiVtJrzuuusmyRKDjs9Dz549065duzz77LM55JBD8re//S2TJ0/+TM9a+PN26tQpnTp1WuyahXu2lEqlvPDCC4vcX1r3VLn+fNZYY43ssccemT17dl1At3DcanlPt/roo4/yl7/8Jf/93/+d3r17Z8stt6zb4PjMM89MkkyZMqVBdfbs2bNB3+/Ro0d+9KMfJUnOOOOMfPDBB/mP//iPxQZmAMDqSaADQCG0b98+STJ9+vSUSqUV/v4HH3xQ9/uF4cLibLDBBous/3cdO3Zc7PWFIzCf3qz389SuXbucffbZadOmTZ544on8/Oc/z84775y+ffvm9NNPz/PPP7/cz1r48y7tz6Z169Z1Y1iL2wtnnXXWWeIx8eX881m4T87tt9+ejz76KCNHjkyLFi2y++67L/O77777bvbZZ5/84Q9/yFNPPZVp06ZljTXWyFprrVVvg+NZs2Y1qMaFI2cN8f3vfz9dunRJ8kmH1Nlnn52mTZs2+LkAwKpBoANAISzcs2bu3Ll59dVXG/SsuXPnlqOklcKuu+6akSNH5vTTT88ee+yRtddeO5MmTcp1112XfffdN3/5y19W6HlF+LPp3bt31l133fzjH//INddck9mzZ6dfv37LdfLZ//7v/+aNN97I+uuvn4svvrhuY+tHHnkko0ePrncEeUM0bty4wc948sknM3HixCRJbW3tEjejBgBWTwIdAAph++23r/v9Z9lY9987Jt56660lrlt4b80111zhd3xWC//y//HHHy/2/rLGlNq1a5eDDjooF1xwQUaPHp1bb701e+yxR0qlUs4777xMmDBhmTUs/HnffvvtJa6ZOXNmZsyYkaQ8HSifVaNGjTJgwIAsWLAgF1xwQZJln26VfBJWLTyF7Oyzz85uu+22yJHjDTmFq5xmzpyZgQMHplQqZfPNN0+SnHnmmZk0aVKVKwMAVhYCHQAKYf31189XvvKVJMlVV11VtyHusiwcz9poo43Spk2bJPWPQP937733Xl34seWWWza05OW2cIzp3XffXez9cePGrdDzttxyy5x77rnZcMMNs2DBgjz55JPL9Z3kkz+Dl19+ebFr/vGPfyT55FSoLbbYYoVqKreFp13Nmzcva6+9dnbaaadlfueDDz6o60DaaqutFrvmscceW+L3F27G/VlG/lbUmWeemTfffDNdunTJjTfemB133DEfffRRTj755Iq8HwBY+Ql0ACiM4447Lk2bNs1bb72VgQMHLnU8aMGCBTn//PPzxBNPJPnkL+ML91i54oorFvvdyy67LHPnzk3btm0/8wlFn0W3bt2SpK575NMuvfTSxV5f2s/fuHHjuv1WltT58++23HLLdO7cOUkyePDgRe7X1tbWjW/ttNNOdeFYtXTv3j3HHntsDj/88AwcOHC5RpxatWpVF8osbmzviSeeyCOPPLLE7y/s5vm8N75+4IEHMnTo0DRu3Dhnn312WrZsmd/+9rdp3bp1xowZkyuvvPJzfT8AUAwCHQAKY6uttsrJJ5+cJLnnnnuy//77Z8SIEZk5c2bdmvfeey9Dhw7NgAED8qc//anecd5HH310WrRokddeey3HHHNM3fjK7NmzM3jw4Fx++eVJPjkaukWLFhX7ub72ta+lpqYmL7zwQs4666y6n+edd97JiSeemGeeeWax37vuuutyxBFH5M4778z7779fd33q1Kk5++yz89prr6VRo0Z1R4YvTU1NTY499tgkya233po//vGPdcHFlClT8rOf/Sxjx45No0aN8uMf/7ihP3JZ/OhHP8pJJ5203KdbtW7dOltvvXWS5NRTT607Qn3evHm5884788Mf/jDt2rVb4vcXnoB22223ZcGCBQ2sfvE++OCDnHLKKUmSI488Mr169UryyWbdv/jFL5Ik5557bl555ZXP5f0AQHE0qXYBALAivv3tb6ddu3b59a9/nRdffDHHH398kqRNmzaZP39+Zs+eXbd22223rTslKEk23njj/P73v8/xxx+fUaNGpW/fvmnbtm1mzZpVd/rSPvvsk8MPP7ySP1K6deuWgw8+OFdddVUuv/zyXHHFFWnTpk1mzJiR5s2b56KLLsr3vve9Rb5XKpXy8MMP5+GHH06StGzZMo0aNaoXcB1//PF1QcSy7LXXXnnhhRdy6aWX5pJLLsmll16a1q1bZ8aMGSmVSmnUqFFOO+20upChiE466aQcdthhee655zJgwIC0bNky8+bNy7x587L55pvngAMOyG9/+9vFfveAAw7IU089lSuvvDLXX3991lprrdTU1GSPPfbISSedVJb6zjjjjEyZMiVbbLFF3bHlC+2333659957c//99+ekk07K9ddfX5bNlwGAYhLoAFA4AwYMyC677JKhQ4fmwQcfzPjx4zNt2rQ0bdo0Xbt2Ta9evbL33nsvdmyqX79+uf322zN48OA8+uijee+999KqVatsueWW+a//+q/079+/Cj9R8stf/jIbb7xxbrzxxrrOmn79+uWYY45Jjx49FvudvfbaKy1btszo0aPz0ksvZcqUKZkzZ07WW2+99OrVK9/+9rfrbSa9PH72s59lxx13zNVXX51//etfmTlzZtZee+1st912Ofzww+s6XIrqS1/6Uq699toMGjQo//znPzNv3rx06tQpe+yxR77//e/n7rvvXuJ399tvv9TW1ubGG2/MhAkT8vbbb6dUKi3xiPsVdeedd2bEiBFp2rRpzj777DRr1myRNb/5zW8yYMCAPP3007nkkkvywx/+sCzvBgCKp6ZkZz0AAACAQrGHDgAAAEDBCHQAAAAACkagAwAAAFAwAh0AAACAghHoAAAAABSMQAcAAACgYAQ6AAAAAAXTpNoFVMuhXfardgkAZTX8g3HVLgGgrD6YPbPaJQCU1fy5b1a7hIqY994r1S5hsZqu3bXaJZSVDh0AAACAghHoAAAAABTMajtyBQAAAHwOahdUu4LVgg4dAAAAgIIR6AAAAAAUjJErAAAAoHxKtdWuYLWgQwcAAACgYAQ6AAAAAAVj5AoAAAAon1ojV5WgQwcAAACgYAQ6AAAAAAVj5AoAAAAom5JTripChw4AAABAwQh0AAAAAArGyBUAAABQPk65qggdOgAAAAAFI9ABAAAAKBgjVwAAAED5OOWqInToAAAAABSMQAcAAACgYIxcAQAAAOVTu6DaFawWdOgAAAAAFIxABwAAAKBgjFwBAAAA5eOUq4rQoQMAAABQMAIdAAAAgIIxcgUAAACUT62Rq0rQoQMAAABQMAIdAAAAgIIxcgUAAACUTckpVxWhQwcAAACgYAQ6AAAAAAVj5AoAAAAoH6dcVYQOHQAAAICCEegAAAAAFIyRKwAAAKB8nHJVETp0AAAAAApGoAMAAABQMEauAAAAgPKpXVDtClYLOnQAAAAACkagAwAAAFAwRq4AAACA8nHKVUXo0AEAAAAoGIEOAAAAQMEYuQIAAADKp9bIVSXo0AEAAAAoGIEOAAAAQMEYuQIAAADKxylXFaFDBwAAAKBgBDoAAAAABWPkCgAAACgfp1xVhA4dAAAAgIIR6AAAAAAUjJErAAAAoGxKpQXVLmG1oEMHAAAAoGAEOgAAAAAFY+QKAAAAKJ+SU64qQYcOAAAAQMEIdAAAAAAKxsgVAAAAUD61Rq4qQYcOAAAAQMEIdAAAAAAKxsgVAAAAUD5OuaoIHToAAAAABSPQAQAAACgYI1cAAABA+dQuqHYFqwUdOgAAAAAFI9ABAAAAKBgjVwAAAED5OOWqInToAAAAABSMQAcAAACgYIxcAQAAAOVTa+SqEnToAAAAABSMQAcAAACgYIxcAQAAAOWzCp5yNXHixAwZMiRjx47N+PHj07Vr1wwbNqzu/qRJk9K3b9/FfrdZs2Z55plnlrquZ8+eufHGG1eoJoEOAAAAwFKMHz8+o0aNSs+ePVNbW5tSqVTvfseOHXPDDTfUu1YqlfK9730vO+ywwyLP+8lPfpLevXvXfW7VqtUK1yTQAQAAAFiK3XbbLf369UuSDBw4MOPGjat3v1mzZunVq1e9a4899lhmzpyZAQMGLPK8jTfeeJH1K0qgAwAAAJTPKnjKVaNGK74F8bBhw9K6devstttun0NFAh0AAABgNbCkPW4WGjlyZNneNW/evNxzzz3Zfffd07x580Xun3766TnhhBPSvn379O3bNyeeeGLat2+/Qu8Q6AAAAACU0YMPPphp06YtMm7VrFmzHHTQQenTp0/atm2bsWPH5s9//nPGjRuXm266KU2bNl3udwh0AAAAgPJZSUeuytmBsyx33HFH1l577ey44471rnfs2DGnn3563eftt98+m2++eY466qjce++96d+//3K/Y8WHwAAAAABYrI8++ij3339/vvGNb6Rx48bLXL/LLrukZcuWefbZZ1foPQIdAAAAgDK59957M2fOnOy1116f63uMXAEAAABlUyotqHYJVTVs2LB07tw5PXv2XK71999/f2bNmpWtt956hd4j0AEAAABYitmzZ2fUqFFJkjfffDMzZ87MXXfdleSTfXA6dOiQJJk6dWoeffTRHHnkkYt9zllnnZWampr06tUrbdu2zdNPP51LLrkkW221Vfr167dCNQl0AAAAAJbi/fffz3HHHVfv2sLPf/3rX9O7d+8kyYgRIzJ//vwljlttuummue6663LjjTdmzpw5WXfddbP//vvn2GOPTZMmKxbR1JRKpdJn+FkK79Au+1W7BICyGv7BuGqXAFBWH8yeWe0SAMpq/tw3q11CRcx+4LJql7BYLb56eLVLKCubIgMAAAAUjEAHAAAAoGDsoQMAAACUT6m22hWsFnToAAAAABSMQAcAAACgYIxcAQAAAOVTa+SqEnToAAAAABSMQAcAAACgYAQ6AAAAAAVjDx0AAACgfBxbXhE6dAAAAAAKRqADAAAAUDBGrgAAAIDycWx5RejQAQAAACgYgQ4AAABAwRi5AgAAAMrHKVcVoUMHAAAAoGAEOgAAAAAFY+QKAAAAKB+nXFWEDh0AAACAghHoAAAAABSMkSsAAACgfIxcVYQOHQAAAICCEegAAAAAFIyRKwAAAKB8SkauKkGHDgAAAEDBCHQAAAAACsbIFQAAAFA+TrmqCB06AAAAAAUj0AEAAAAoGCNXAAAAQPk45aoidOgAAAAAFIxABwAAAKBgjFxBA2yxw3/k5Ov/Z7H3/mffgXn5qfF1nzf7QvccePIh2Xirrpk9c1bGDHskQ8+5Nh/PmlOpcgGWqVWrlvnRsUfki1/qmW2/uHXWXLN9fvyDgbn+2lvrrTv40ANywH/tnc26dU27dm3zzjuT88hDj+Wcsy/KG6+/WaXqAZbPllt2y2mn/jRf2HbrrLdex8yaNTvPP/9S/vDHP2fYnfdWuzwoPqdcVYRAB8rgnsvvzKtjJ9S79u5r79T9vvOWXXLStb/KWxPezHW/uSId1lsrX//+3llvk/Xzh8P+t9LlAixRh7XWzM8GHpM3Xn8zzz7zYvp8pfdi1229zZZ5feKk3DXi75k+bUY6b9wphxx6QHb/+q756k775N13Jle4coDlt3HnTmnTulWuuvqmvPXWu2nZskX+c9/+ue3WK3L0D36eS4dcU+0SAZZJoANl8OKY5/LEiH8s8f7+P/t2Ppr+Uc7879MyZ+bsJMl7kybn8LN/mK127plxD42tVKkAS/XuO5PzH5vvlMmT30vPbbfKfQ/cvNh1J/30jEWuDb/zvowcdUsOPGifXHDu4M+7VIDPbMRdf8+Iu/5e79pFf7o8Yx67K8cf/32BDlAI9tCBMlmj1Rpp1HjR/5Nao3WL/EefbfLIrQ/WhTlJ8vAtozJ75uxsv+eXK1kmwFLNnTsvkye/95m++8bET0at2rVrW86SACqitrY2kya9lfb+MwwarlS7cv5axejQgTL43jnHpEXrFlkwf0Feevz5XP/bv+a1Z15OkmzUvXOaNG1S93mhBfPm5/XnXs3G/7FJNUoGKIs112yfxo0bZcONNsiJP/9RkuTBUY9WuSqA5dOyZYu0aLFG2rVrm70GfC1f32PX3HjT7dUuC2C5FC7Q+eCDDzJhwoRst9121S4FMn/u/Dw+/NGMvf+fmfnBjGyw+Ub5xpF755c3/Tq/3u+Xef3ZV9Ou45pJkmmTP1jk+9MnT0u37XtUumyAsnn6hQezxhrNkyTvv/9BTv7ZrzPq/keqXBXA8jnnd7/KUd8/JEmyYMGC3HrbiBx73ClVrgpg+RQu0BkzZkyOP/74PP/889UuBTLhny/mwh++WPf5qfueyOPDH81v7vpjDvj5t/OHQ3+TZv//Lzrz585b5PvzPp6bpms0q1i9AOX23/sfmTWaN8/m3bvmgAP3TstWLapdEsByu2DQ4Nxyy51Zf4N1c8B+e6Vx40Zp1qxptcuC4nPKVUUULtCBld3kie/kqXsfzxf36J2aRo0yd87HSZImi/kvB02bN8u8OXMrXSJA2Yx+6LEkycj7Hsxdw0fmwUeH5aOZszJksA1FgZXfiy++nBdf/GQs/uqrh2bEndfmb7dekR13GlDlygCWbaUJdPbaa6/lWvfRRx99zpVAw73/1ntp2rxpmrdsnun/f9Sq/f8fvfp37Tq2z7R3p1a6PIDPxWuvvpFnnn4u+/3XXgIdoJBuvuXO/Pni36Vbt03z0ksvL/sLAFW00gQ6r7zySjbbbLNsueWWS1335ptv5u23365QVfDZdOy8bubO+TgffzQnk156I/PnzU+XrTfNmDv/b1+Jxk2bpPOWm9S7BlB0LVqskWbNjJICxdSixRpJknZt21S5Eig4I1cVsdIEOptvvnk23njjnHnmmUtdd/fdd+fxxx+vUFWwdG06tM2HU2fUu7ZRj42zbb8v5elRT6VUKmX2h7Py3Oin8+V9v5LbB92UOR/NSZLstO8uadG6RR4fLtABiqVx48Zp3aZVpk+r/59/235h6/TYsltuvmlYlSoDWD7rrLNWpkx5v961Jk2a5OCD98+sWbPz3PMvVakygOW30gQ622yzTR566KHlWlsqlT7namD5/PDCn2TunLmZ8OSLmfH+9Gy4ead89aDd8/GcubnxrKvr1g0959qccstvc/INv84D192bDuutla8fuVeeefBfeWbUv6r3AwAsxhFHfjvt2rXNuut3TJLs8Y1ds8EG6yVJBv/lqtTU1GTssw/ktltH5IXnx2fWrNnZcstu+e9v/2dmzPgwf/zdn6pZPsAyXfyns9O2TZs89PA/8uab72S99TrmoIP2TY8tNs+JPzsjH300q9olAixTTWklSUdef/31jB8/Pn379l3qujlz5uT999/Phhtu2KD3HdplvwZ9H5Jk98P6Z8dv7px1N14/a7RukQ+nzshzo5/JbeffmMkT36m3dvMvbZEDBx6SjbfaJHNmzsmYOx/JTb+7uq5jBxpq+Afjql0Cq4gnnx6Zzht3Wuy9L2y9W955e3J+9T8/y047907nzhtmjRbN887bk/PgqEfzx3Muzhuvv1nhillVfTB7ZrVLYBX1X/+1dw4/7KBstdUWWWutNfPhhzPzz38+kwv/dFmGDbu32uWxCps/d/X4/5Gzbzij2iUsVosDf1XtEspqpQl0Kk2gA6xqBDrAqkagA6xqBDrVtaoFOo2qXQAAAAAAK2al2UMHAAAAWAU45aoidOgAAAAAFIxABwAAAKBgjFwBAAAA5WPkqiJ06AAAAAAUjEAHAAAAoGCMXAEAAADlUzJyVQk6dAAAAAAKRqADAAAAUDBGrgAAAIDyccpVRejQAQAAACgYgQ4AAABAwRi5AgAAAMqnVKp2BasFHToAAAAABSPQAQAAACgYI1cAAABA+TjlqiJ06AAAAAAUjEAHAAAAoGCMXAEAAADlY+SqInToAAAAABSMQAcAAACgYIxcAQAAAOVTMnJVCTp0AAAAAApGoAMAAABQMEauAAAAgLIp1ZaqXcJqQYcOAAAAQMEIdAAAAAAKxsgVAAAAUD61TrmqBB06AAAAAAUj0AEAAAAoGCNXAAAAQPmUjFxVgg4dAAAAgIIR6AAAAAAUjJErAAAAoHxqS9WuYLWgQwcAAACgYAQ6AAAAAAVj5AoAAAAon1qnXFWCDh0AAACAghHoAAAAABSMkSsAAACgfFbBkauJEydmyJAhGTt2bMaPH5+uXbtm2LBh9dYccsghGTNmzCLfHT58eDbddNO6zx9++GHOPPPM3HfffZk3b1523nnnnHLKKenYseMK1STQAQAAAFiK8ePHZ9SoUenZs2dqa2tTKi3+aPYvfOELOemkk+pd69SpU73Pxx9/fCZMmJDTTz89zZs3z3nnnZcjjzwyN998c5o0Wf6YRqADAAAAsBS77bZb+vXrlyQZOHBgxo0bt9h1bdu2Ta9evZb4nKeeeioPP/xwhgwZkj59+iRJNtlkk/Tv3z/33HNP+vfvv9w12UMHAAAAKJ9SaeX81QCNGpUnPnnwwQfTtm3b7LTTTnXXunbtmh49euTBBx9csZrKUhEAAADAam7MmDHp1atXtt566xx88MF5/PHH691/5ZVXsskmm6Smpqbe9a5du+aVV15ZoXcZuQIAAABWeX379l3q/ZEjRzbo+dttt1322WefdOnSJZMnT86QIUPy3e9+N1dddVW23XbbJMmMGTPSpk2bRb7brl27JY5xLYlABwAAACifVfCUq+Vx7LHH1vv81a9+NQMGDMif/vSnDB48uOzvE+gAAAAAq7yGduCsqJYtW2aXXXbJ3XffXXetbdu2eeeddxZZO3369LRr126Fnm8PHQAAAIAK6Nq1a1599dVFjj1/9dVX07Vr1xV6lkAHAAAAKJ/a0sr5q8JmzZqVBx54IFtvvXXdta985SuZPn16Hn300bprr776ap577rl85StfWaHnG7kCAAAAWIrZs2dn1KhRSZI333wzM2fOzF133ZUk2X777fPKK6/k0ksvze67754NN9wwkydPzuWXX54pU6bk/PPPr3vOtttumz59+uQXv/hFTjrppDRv3jznnntuunfvnq997WsrVJNABwAAAGAp3n///Rx33HH1ri38/Ne//jXrrbde5s2bl3PPPTfTpk1LixYtsu222+aMM87INttsU+975513Xs4888ycdtppmT9/fvr06ZNTTjklTZqsWERTU/r04NZq4tAu+1W7BICyGv7Bih1zCLCy+2D2zGqXAFBW8+e+We0SKmLWOYdXu4TFavmzy6pdQlnZQwcAAACgYAQ6AAAAAAVjDx0AAACgfKpwotTqSIcOAAAAQMEIdAAAAAAKxsgVAAAAUDal2tpql7Ba0KEDAAAAUDACHQAAAICCMXIFAAAAlI9TripChw4AAABAwQh0AAAAAArGyBUAAABQPiWnXFWCDh0AAACAghHoAAAAABSMkSsAAACgfJxyVRE6dAAAAAAKRqADAAAAUDBGrgAAAIDyqXXKVSXo0AEAAAAoGIEOAAAAQMEYuQIAAADKxylXFaFDBwAAAKBgBDoAAAAABWPkCgAAACifklOuKkGHDgAAAEDBCHQAAAAACsbIFQAAAFA+TrmqCB06AAAAAAUj0AEAAAAoGCNXAAAAQNmUap1yVQk6dAAAAAAKRqADAAAAUDBGrgAAAIDyccpVRejQAQAAACgYgQ4AAABAwRi5AgAAAMrHyFVF6NABAAAAKBiBDgAAAEDBGLkCAAAAyqdUW+0KVgs6dAAAAAAKRqADAAAAUDBGrgAAAIDyccpVRejQAQAAACgYgQ4AAABAwRi5AgAAAMqmZOSqInToAAAAABSMQAcAAACgYIxcAQAAAOVj5KoidOgAAAAAFIxABwAAAKBgjFwBAAAA5VNbW+0KVgs6dAAAAAAKRqADAAAAUDBGrgAAAIDyccpVRejQAQAAACgYgQ4AAABAwRi5AgAAAMrHyFVF6NABAAAAKBiBDgAAAEDBGLkCAAAAyqZUMnJVCTp0AAAAAApGoAMAAABQMEauAAAAgPJxylVF6NABAAAAKBiBDgAAAEDBGLkCAAAAysfIVUXo0AEAAAAoGIEOAAAAQMEYuQIAAADKpmTkqiJW20Dnurcfq3YJAGU15VtbVLsEgLLa5vbJ1S4BAFZaRq4AAAAACma17dABAAAAPgdGripChw4AAABAwQh0AAAAAArGyBUAAABQPrXVLmD1oEMHAAAAoGAEOgAAAAAFY+QKAAAAKJuSU64qQocOAAAAQMEIdAAAAAAKxsgVAAAAUD5GripChw4AAABAwQh0AAAAAArGyBUAAABQPrXVLmD1oEMHAAAAoGAEOgAAAAAFY+QKAAAAKJuSU64qQqADAAAAsBQTJ07MkCFDMnbs2IwfPz5du3bNsGHD6u7PnDkzl19+eUaNGpXXXnstzZo1yzbbbJMTTjgh3bt3r1s3adKk9O3bd5Hn9+zZMzfeeOMK1STQAQAAAFiK8ePHZ9SoUenZs2dqa2tTKtXvQnrrrbdyww03ZL/99svxxx+fjz/+OJdddlkOPPDA3Hzzzdl0003rrf/JT36S3r17131u1arVCtck0AEAAADKZxU85Wq33XZLv379kiQDBw7MuHHj6t3v1KlT7r333rRo0aLu2g477JDddtst1157bU499dR66zfeeOP06tWrQTUJdAAAAACWolGjpZ8p1bJly0WutWrVKp07d87kyZM/n5o+l6cCAAAArMZmzJhRt9/Op51++unp0aNHdtxxx5xyyimZNm3aCj9fhw4AAABQNivrKVeL24z4340cObKs7zvnnHNSU1OTgw46qO5as2bNctBBB6VPnz5p27Ztxo4dmz//+c8ZN25cbrrppjRt2nS5ny/QAQAAACijm2++OTfeeGPOOuusrLfeenXXO3bsmNNPP73u8/bbb5/NN988Rx11VO699970799/ud8h0AEAAABWeeXuwFmSUaNG5bTTTssPf/jD7Lvvvstcv8suu6Rly5Z59tlnBToAAABAlayCp1wtr3/961857rjj8s1vfjPHHXfc5/oumyIDAAAANNCECRNy1FFHZYcddsgZZ5yx3N+7//77M2vWrGy99dYr9D4dOgAAAABLMXv27IwaNSpJ8uabb2bmzJm56667knyyD06pVMoRRxyR5s2b59BDD824cePqvtu6detsttlmSZKzzjorNTU16dWrV9q2bZunn346l1xySbbaaqv069dvhWoS6AAAAABlU1oFR67ef//9RUaoFn7+61//miR55513kiSHHXZYvXXbb799rrrqqiTJpptumuuuuy433nhj5syZk3XXXTf7779/jj322DRpsmIRTU2pVFo5zxP7nDVr3qnaJQCU1ZRvbVHtEgDKapvbJ1e7BICymvj+09UuoSLe32uXapewWGvdMaraJZSVPXQAAAAACsbIFQAAAFA+q+DI1cpIhw4AAABAwQh0AAAAAArGyBUAAABQNqviKVcrIx06AAAAAAUj0AEAAAAoGCNXAAAAQPkYuaoIHToAAAAABSPQAQAAACgYI1cAAABA2TjlqjJ06AAAAAAUjEAHAAAAoGCMXAEAAABlY+SqMnToAAAAABSMQAcAAACgYIxcAQAAAGVj5KoydOgAAAAAFIxABwAAAKBgjFwBAAAA5VOqqXYFqwUdOgAAAAAFI9ABAAAAKBgjVwAAAEDZOOWqMnToAAAAABSMQAcAAACgYIxcAQAAAGVTqnXKVSXo0AEAAAAoGIEOAAAAQMEYuQIAAADKxilXlaFDBwAAAKBgBDoAAAAABWPkCgAAACibUskpV5WgQwcAAACgYAQ6AAAAAAVj5AoAAAAoG6dcVYYOHQAAAICCEegAAAAAFIyRKwAAAKBsSrVOuaoEHToAAAAABSPQAQAAACgYI1cAAABA2ZRK1a5g9aBDBwAAAKBgBDoAAAAABWPkCgAAACgbp1xVhg4dAAAAgIIR6AAAAAAUjJErAAAAoGyMXFWGDh0AAACAghHoAAAAABSMkSsAAACgbEqlalewetChAwAAAFAwAh0AAACAgjFyBQAAAJSNU64qQ4cOAAAAQMEIdAAAAAAKxsgVAAAAUDalkpGrSihboDN79uxMmzYtpcWcT7bBBhuU6zUAAAAAq70GBTq1tbW59NJLc9VVV+W9995b4rrnn3++Ia8BAAAA4N80KND5/e9/n8suuyybb7559thjj7Rv375MZQEAAABFVKqtdgWrhwYFOrfffnt23nnnDB48uFz1AAAAALAMDTrlasaMGenbt2+5agEAAABgOTSoQ6dbt26ZMmVKuWoBAAAACq7WKVcV0aAOnWOOOSbXX3993n777XLVAwAAAMAyNKhDZ9y4cdlggw3Sv3//7L777unUqVMaNaqfEdXU1ORHP/pRg4oEAAAA4P80KNC58MIL635/++23L3aNQAcAAABWHyUjVxXRoEBn5MiR5aoDAAAAgOXUoEBnww03LFcdAAAAACynBgU6/+6DDz7IpEmTkiSdOnXKmmuuWa5HAwAAAAVRqjVyVQkNDnReeOGF/OY3v8mTTz5Z7/qXvvSl/PKXv8wWW2zR0FcAAAAA8G8aFOi89NJLOeiggzJ37tz07ds3m222WZJkwoQJuf/++/Ptb387119/fTbffPOyFAsAAABAAwOdCy64IE2bNs111123SCfOSy+9lIMPPjgXXHBBBg0a1KAiAQAAgGIolapdweqhUUO+/Pjjj+db3/rWYsequnXrloMOOihjxoxpyCsAAAAA+JQGBTqzZ8/OOuuss8T7HTt2zOzZsxvyCgAAAAA+pUGBzkYbbZT7779/iffvv//+bLTRRg15BQAAAFAgpdqalfLXqqZBgc4+++yThx9+OD/96U8zfvz4LFiwIAsWLMhLL72Un/70pxk9enT23XffctUKAAAAQBq4KfIRRxyR5557LnfeeWeGDx+eRo0+yYdqa2tTKpXyjW98I4cffnhZCgUAAADgEw0KdBo3bpzzzjsvo0ePzn333ZdJkyYl+WQUq1+/fvnyl79cliIBAACAYqgtrXrjTSujBgU6C+20007ZaaedyvEoAAAAAJahQXvoAAAAAFB5K9Shc+GFF6ampiY/+MEP0qhRo1x44YXL/E5NTU1+9KMffeYCAQAAgOIoGbmqiJpSqVRa3sVbbLFFampqMnbs2DRr1ixbbLHFsl9QU5Pnn3++QUV+Hpo171TtEgDKasq3lv2fyQBFss3tk6tdAkBZTXz/6WqXUBHPbLJXtUtYrK1fvaPaJZTVCnXojBw5MknSrFmzep8BAAAAqJwVCnQ23HDDpX4GAAAAVm/LPwdEQzRoU+TvfOc7efTRR5d4/x//+Ee+853vNOQVAAAAAHxKgwKdMWPG5L333lvi/alTp+bxxx9vyCsAAAAA+JQVGrlaUTNmzKjbbwcAAABY9dU65aoiVjjQeeGFF/LCCy/UfX7iiSeyYMGCRdZNmzYt1113XTbddNOGVQgAAABAPSsc6Nx333258MILk3xyJPkNN9yQG264YbFrW7VqlV/+8pcNqxAAAACgiiZOnJghQ4Zk7NixGT9+fLp27Zphw4Ytsu6mm27KpZdemrfeeiubbLJJTjjhhOy666711nz44Yc588wzc99992XevHnZeeedc8opp6Rjx44rVNMKBzr77rtvtt9++5RKpRx66KE56qijstNOO9VbU1NTk5YtW2azzTZL8+bNV/QVAAAAQEGVVsGRq/Hjx2fUqFHp2bNnamtrU1rMUV533nlnTj311Bx99NHZYYcdMnz48BxzzDG55ppr0qtXr7p1xx9/fCZMmJDTTz89zZs3z3nnnZcjjzwyN998c5o0Wf6YZoUDnQ033LDuuPIzzzwzX/rSl7LRRhut6GNglfWVr+yY++69abH3+uy8d8aM+WeFKwJYguZrpPk3/iuNu/ZI4026p1Hrtpl16e8yb/Q99ZY1/Ur/NNuxbxqt3zk1LVulNO39zH9hbOb87aqU3n+33tpmu+6VJj16pXHXHmm0VsfMffjuzB5yTiV/KoB6WrZqkaOO+W56fXHr9PrCVmm/Zrv89JhTMvS62xdZu+c+X8v3fvidbLp5l9QuqM2Lz0/IJYMuz9/vfagKlQMrk9122y39+vVLkgwcODDjxo1bZM0FF1yQPffcM8cff3ySZIcddshLL72Uiy66KIMHD06SPPXUU3n44YczZMiQ9OnTJ0myySabpH///rnnnnvSv3//5a6pQZsi77XXXpkzZ84S78+cOTNrrLHGCiVMsKoYdOGQPPnE2HrXXn751SpVA7ComtbtssY+30nte++m9o1X0qhHr8Wua7zxZql9753M+9ejKc2amUZrr5dmu/RP6147ZOZpR6U07f26tc37H5is0TILXnkhNe06VOgnAViyDh3WzPE/PzqT3ngrz497MTvuvP1i1x125EE546yTM/LuUTn7ur+lefPm2f+gvXP59RflqENPyF3DRla4cmBl0qjR0g8Jf+ONN/Laa6/lZz/7Wb3r/fv3z+9+97vMnTs3zZo1y4MPPpi2bdvWm3Tq2rVrevTokQcffLBygc5ZZ52Vhx56KHffffdi7++3337ZddddM3DgwIa8Bgpp9MNjcsutd1a7DIAlKk2fmhnHHZDSjA/SuEu3tP7Vnxa7bs5VFyxybd4/R6fN6Ren2Zd3z8fDr6+7PvOsn6T0/uQkSduL7/h8CgdYAZPfnZIv9dg1Uya/n617bZlhI69f7LpDv3dQ/vXPZ3L4t35cd+3Ga2/NY+Puy37/vbdAB1bAYqaRVnmvvPJKkk+6bf7dpptumnnz5uWNN97IpptumldeeSWbbLJJamrqj6V17dq17hnLq0GBzsMPP5yvfe1rS7y/xx575L777hPosNpq3bpVZs+es9iT4ACqbv68lGZ88Jm+Wnrv/49atWxd//r/D3MAVhZz587LlMnvL3Nd6zat8+rLE+tdm/nhR5k1c1bmzF7yVAJQHH379l3q/ZEjP3twO3369CRJ27Zt611f+Hnh/RkzZqRNmzaLfL9du3aLHeNamqX3DC3DO++8k86dOy/x/kYbbZS33367Ia+Awho8+A+Z+v6L+XDGy7nn7hvzhS9sU+2SABqkplXb1LRpn8ZduqXFEScmSRY8Z18wYNXwj9GPZ5e+O+WwIw9Kp402yKabd8mvf/eLtGnbOpdfck21ywNYRIM6dJo2bZrJk5f8b+KmTJmyzDkzWNXMnTs3t9xyZ0bc9fe8//7U9NiiW0444ajc//dbsssu++RfY5+tdokAn0mbc69PTdNmSZLaD6dn9tUXZr5AB1hFnH7y2emw1po546yTc8ZZJydJ3n9var6175H55xNPV7k6KJbalfSUq4Z04CxLu3btknxyJPk666xTd33GjBn17rdt2zbvvPPOIt+fPn163Zrl1aBAZ4sttshdd92VI488Ms2aNat3b968eRkxYkS6d+++ws+dNWtWWrZsudh78+bNy5QpU7LBBht8pprh8/aPfzyZ//7HUXWfhw27N7fcemeefOLe/Po3J2evvQ6uYnUAn91Hfzw5NU2bpdH6ndPsy/1S03yNapcEUDazZ8/OKxNey9tvvZu/3/1gWrVpmSOOPiSXXHlu9h9wWCa++ka1SwRWYl27dk3yyV46C3+/8HPTpk3rTgfv2rVrHn300ZRKpXr76Lz66qvp1q3bCr2zQe0zBx98cMaPH5+jjjoqzzzzTObOnZt58+blmWeeyVFHHZUJEybk4IOX/y+vF110Ubbbbrt88YtfzFe/+tVcddVVi6x57rnnljn3Biubl19+LXfccXe+usuOutaAwlrwwtjMf+bxzL3n5sy66H/SfJ9D0qzvPtUuC6AsLr7sD9lgw/Vz4jGnZvgd9+ama/+WA/c+PE2bNc3PfvnjZT8AWK1ttNFG6dKlS+66665614cPH54dd9yxrgnmK1/5SqZPn55HH320bs2rr76a5557Ll/5yldW6J0N6tDZY489ctRRR+WSSy7Jf/3Xf6WmpiY1NTWpra1NqVTKkUceudxHbt1888256KKLsv/++6dHjx554okncuaZZ+aBBx7I+eefn9atWy/7IbASmzTp7TRv3jytWrXMhx/OrHY5AA1SO+XtLHh9Qpru0DdzR/6t2uUANMhGG2+Yr/brk5OOP6Pe9enTZuTxx57Kl3pvW6XKoJhKK+nIVUPMnj07o0aNSpK8+eabmTlzZl14s/3226dDhw758Y9/nBNPPDGdO3dO7969M3z48Dz99NO5+uqr656z7bbbpk+fPvnFL36Rk046Kc2bN8+5556b7t27L/XQqcVpUKCTJCeccEL69u2b22+/Pa+//nqSpEuXLhkwYEC22Wb5N4G96qqrcuSRR+aEE05Ikhx00EE56KCD8pOf/CQHH3xwBg8eXG8ODYpmk006Z/bsOZk586NqlwJQFjVNmydNmla7DIAGW2edtZIkjRsv2kndtEmTNG7cuNIlASuZ999/P8cdd1y9aws///Wvf03v3r0zYMCAzJ49O4MHD85f/vKXbLLJJrnwwguz7bb1Q+HzzjsvZ555Zk477bTMnz8/ffr0ySmnnJImTVYsomlwoJMk22yzzQqFN4szceLEfPnLX6537Utf+lJuvPHGHHnkkTnwwANz6aWXNugdUAlrr90h7703td61bbbukQEDds/dd9+fUqlUpcoAPoNGjZI1Wiaz6ncWNt6kexp12iTz/vH3KhUGUD6vvfpGFixYkL2+uUeuueKmuuvrbbButtvxC3niH09VsTpgZdCpU6e8+OKLy1x3wAEH5IADDljqmjZt2uS3v/1tfvvb3zaoprIEOuXQtm3bTJ06dZHr6623Xq699tp8//vfz7e+9a0cffTRVagOlt81V1+c2XPm5B+PPpHJU95Pjx6b53tHfDuzZs3OL085s9rlAdTTrO8+qWnZOjXtP/m300177ZhGHT7piP34vtuSJG3/cF3mjXkgC958LZk7J406bZJmffZIafZH+fiOq+s9r0nPHdK486affGjcOI036prme307STLvqUdSO+nVivxcAP/u0O/9d9q2a5N11+uYJOm3x1ez/gbrJkmu+Mt1mfr+B7nxmtty0Hf2y3W3XZq7ht2XVq1b5ZDDD8waazTPRecNqWb5UDgr6ylXq5qa0gq0C1x44YWpqanJD37wgzRq1CgXXnjhsl9QU5Mf/ehHy1z3wx/+MC1atMgf/vCHxd7/+OOPc9xxx+WBBx5ITU1Nnn/++eUte7GaNe/UoO/DkvzoR4fnoP/eN5tu2iVt27bOlCnv5/77R+c3/3tuXn75tWqXxypsyre2qHYJFFCbc65Oo7XXW+y9GSd+O6Vp72eN/zoyTbbo9cm6Zs1SmvZ+5j/3z8y5/ZqU3n+33ndaHPGzNOuzx2KfN+vS32Xe6HvK/jOw6trm9snVLoFVxMNPjchGnTdc7L2den09k954K40bN87B3z0gB35732zctXOS5Omnns0Fv78kjz78eCXLZRU28f2nq11CRTy2wX9Wu4TF6v3WLdUuoaxWKNDZYostUlNTk7Fjx6ZZs2bZYotl/+VhecOXESNG5Morr8yf//zntG/ffrFrFixYkNNPPz2jR4/O3//esBZvgQ6wqhHoAKsagQ6wqhHoVNdqHei8+eabSZINN9yw3udlWbh+ZSLQAVY1Ah1gVSPQAVY1q0ug84+VNNDZYRULdFZoD51PBzMrY1ADAAAAsKpb9Fw+AAAAAFZqK9ShszybIH/a8m6KDAAAABSfU64qo8GBTk3NJ/+gPr0VT01NTUqlkkAHAAAAoMxWKNAZOXJkvc+zZs3KSSedlMaNG+ewww7LpptumiSZMGFCrrjiitTW1uZ3v/td+aoFAAAAoGGbIv/mN79Js2bNcvXVV6dJk/971BZbbJE99tgjBx98cK6//vqccsop5akWAAAAWKmVjFxVRIM2RR4xYkT69+9fL8xZqGnTpunfv3/uuuuuhrwCAAAAgE9pUKAzc+bMfPjhh0u8/+GHHy71PgAAAAArrkGBTo8ePXLNNdfk9ddfX+TexIkTc80112TLLbdsyCsAAACAAqldSX+talZoD51PO/HEE3P44Ydnzz33TL9+/bLJJpskSV555ZWMHDkyNTU1+elPf1qWQgEAAAD4RIMCnS996Uu56qqrcuaZZ2bEiBH17vXq1SsDBw5Mr169GvIKAAAAAD6lQYFOkvTs2TPXX399pk6dmjfeeCNJ0qlTp6y11loNLg4AAAAollKcclUJDQ50FurQoUM6dOhQrscBAAAAsAQN2hQ5SRYsWJDbbrstJ554Yr773e/mueeeS5JMnz49t912W959990GFwkAAADA/2lQh87s2bNz+OGH56mnnkqLFi0yZ86cTJ8+PUnSunXr/P73v89+++2XE044oSzFAgAAACu32lK1K1g9NKhDZ9CgQRk3blwuvPDCjBw5MqXS//1Ta9y4cb72ta/l4YcfbnCRAAAAAPyfBgU6d911Vw488MD069cvNTWLbnrUuXPnvPnmmw15BQAAAACf0qCRq8mTJ6d79+5LvN+iRYt89NFHDXkFAAAAUCC1TrmqiAZ16LRv336pmx6PHz8+HTt2bMgrAAAAAPiUBgU6O+64Y2655ZbMnj17kXtvvPFGbr755uy8884NeQUAAAAAn9Kgkatjjjkm++23X/bff//sueeeqampyUMPPZRHHnkk119/fZo1a5ajjjqqXLUCAAAAK7mSkauKaFCHzsYbb5wrrrgijRs3zgUXXJBSqZTLLrssgwcPznrrrZcrr7wy66+/frlqBQAAACAN7NBJkq222iq33357Xnrppbz88ssplUrp0qVLttxyy3LUBwAAAMCnfOZA56OPPso+++yTgw8+OIcddli6deuWbt26lbM2AAAAoGBqq13AauIzj1y1atUq06ZNS6tWrcpZDwAAAADL0KA9dHr27JlnnnmmXLUAAAAAsBwaFOiceOKJueuuu3LzzTenVCqVqyYAAACgoEqpWSl/rWoatCnymWeembZt2+aUU07JOeeck86dO2eNNdaot6ampiZXXnllg4oEAAAA4P80KNCZNGlSktQdTf7ee+81vCIAAAAAluozBzpTp07NueeemzXXXDOdO3cuZ00AAABAQTnlqjJWONCpra3N6aefnqFDh9btm9OrV69cdNFF6dChQ9kLBAAAAKC+Fd4U+eqrr86NN96YtddeO7vvvnu6deuWp556KqeddtrnUR8AAAAAn7LCHTq33XZbNt1009xwww1p3bp1kuSUU07JrbfemhkzZqRt27ZlLxIAAAAoBiNXlbHCHTqvvvpq9t1337owJ0kOPvjgLFiwIK+99lo5awMAAABgMVY40Jk9e3Y6duxY79rCz7NmzSpPVQAAAAAs0Wc65aqmpmaxnxdukgwAAACsnkqpWfYiGuwzBTqjRo3Ke++9V/d59uzZqampyV133ZUXXnih3tqampocdthhDSoSAAAAgP/zmQKdYcOGZdiwYYtcv+GGGxa5JtABAAAAKK8VDnT++te/fh51AAAAAKuAWhNXFbHCgc7222//edQBAAAAwHJa4VOuAAAAAKiuz7SHDgAAAMDi1DrlqiJ06AAAAAAUjEAHAAAAoGCMXAEAAABlU6p2AasJHToAAAAABSPQAQAAACgYI1cAAABA2dRWu4DVhA4dAAAAgIIR6AAAAAAUjJErAAAAoGxqa2qqXcJqQYcOAAAAQMEIdAAAAAAKxsgVAAAAUDalahewmtChAwAAAFAwAh0AAACAgjFyBQAAAJRNbbULWE3o0AEAAAAoGIEOAAAAQMEYuQIAAADKpram2hWsHnToAAAAABSMQAcAAACgYIxcAQAAAGVTGzNXlaBDBwAAAKBgBDoAAAAABWPkCgAAACibUrULWE3o0AEAAAAoGIEOAAAAQMEYuQIAAADKptYhVxWhQwcAAACgYAQ6AAAAAAVj5AoAAAAom9pqF7Ca0KEDAAAAUDACHQAAAICCMXIFAAAAlE2p2gWsJnToAAAAABSMQAcAAACgYIxcAQAAAGVTW1PtClYPOnQAAAAACkagAwAAAFAwRq4AAACAsqmtdgGrCR06AAAAAAUj0AEAAAAoGCNXAAAAQNkYuaoMgQ4AAADAUhxyyCEZM2bMYu/98Y9/zJ577rnENcOHD8+mm25a9poEOgAAAABL8atf/SozZ86sd+3KK6/MPffckx133LHu2he+8IWcdNJJ9dZ16tTpc6lJoAMAAACUTamm2hWU32abbbbItZ/+9KfZaaed0qFDh7prbdu2Ta9evSpSk02RAQAAAFbAP//5z0yaNCl77bVX1WoQ6AAAAACsgGHDhqVly5bp27dvvetjxoxJr169svXWW+fggw/O448//rnVYOQKAAAAWOV9Onz5tJEjRy7Xc+bPn58RI0Zkt912S8uWLeuub7fddtlnn33SpUuXTJ48OUOGDMl3v/vdXHXVVdl2220bVPviCHQAAACAslnVjy0fPXp0pk6dmgEDBtS7fuyxx9b7/NWvfjUDBgzIn/70pwwePLjsdQh0AAAAgFXe8nbgLMuwYcPSvn379OnTZ6nrWrZsmV122SV33313Wd77afbQAQAAAFgOc+bMyX333Zevf/3radq0aVVr0aEDAAAAlM2qPHL197//PbNmzVqu061mzZqVBx54IFtvvfXnUotABwAAAGA53HHHHdlggw3yxS9+sd71J554Ipdeeml23333bLjhhpk8eXIuv/zyTJkyJeeff/7nUotABwAAAGAZpk+fnoceeiiHHnpoampq6t1bZ511Mm/evJx77rmZNm1aWrRokW233TZnnHFGttlmm8+lHoEOAAAAUDalahfwOWnXrl3GjRu32Hsbb7xxhgwZUtF6bIoMAAAAUDACHQAAAICCMXIFAAAAlE1tzbLX0HA6dAAAAAAKRqADAAAAUDBGrgAAAICyqa12AasJHToAAAAABSPQAQAAACgYI1cAAABA2Ri5qgwdOgAAAAAFI9ABAAAAKBgjVwAAAEDZlKpdwGpChw4AAABAwQh0AAAAAArGyBUAAABQNrU11a5g9aBDBwAAAKBgBDoAAAAABWPkCgAAACib2moXsJrQoQMAAABQMAIdAAAAgIIxcgUAAACUTanaBawmdOgAAAAAFIxABwAAAKBgjFwBAAAAZVNr6KoidOgAAAAAFMxq26FTW5IYAquW7YZNq3YJAGU14cXbql0CAKy0VttABwAAACi/2moXsJowcgUAAABQMAIdAAAAgIIxcgUAAACUjR1rK0OHDgAAAEDBCHQAAAAACsbIFQAAAFA2TrmqDB06AAAAAAUj0AEAAAAoGCNXAAAAQNnU1lS7gtWDDh0AAACAghHoAAAAABSMkSsAAACgbGpTqnYJqwUdOgAAAAAFI9ABAAAAKBgjVwAAAEDZGLiqDB06AAAAAAUj0AEAAAAoGCNXAAAAQNnUVruA1YQOHQAAAICCEegAAAAAFIyRKwAAAKBsap1zVRE6dAAAAAAKRqADAAAAUDBGrgAAAICyMXBVGTp0AAAAAApGoAMAAABQMEauAAAAgLKprXYBqwkdOgAAAAAFI9ABAAAAKBgjVwAAAEDZ1DrnqiJ06AAAAAAUjEAHAAAAoGCMXAEAAABlY+CqMnToAAAAABSMQAcAAACgYIxcAQAAAGVTW+0CVhM6dAAAAAAKRqADAAAAUDBGrgAAAICyKTnnqiJ06AAAAAAUjEAHAAAAoGCMXAEAAABl45SrytChAwAAAFAwAh0AAACAgjFyBQAAAJRNrVOuKkKHDgAAAEDBCHQAAAAACsbIFQAAAFA2Bq4qQ4cOAAAAQMEIdAAAAAAKxsgVAAAAUDZOuaoMHToAAAAABSPQAQAAACgYI1cAAABA2dRWu4DVhA4dAAAAgIIR6AAAAAAUjJErAAAAoGxKTrmqCB06AAAAAAUj0AEAAAAoGCNXAAAAQNk45aoydOgAAAAALMUtt9yS7t27L/Lr97//fb11N910U/bYY49svfXW2XvvvXP//fd/bjXp0AEAAABYDpdeemnatGlT93ndddet+/2dd96ZU089NUcffXR22GGHDB8+PMccc0yuueaa9OrVq+y1CHQAAACAslmVT7n6j//4j3To0GGx9y644ILsueeeOf7445MkO+ywQ1566aVcdNFFGTx4cNlrMXIFAAAA0ABvvPFGXnvttXzjG9+od71///559NFHM3fu3LK/U6ADAAAAsBwGDBiQHj16pG/fvrnkkkuyYMGCJMkrr7ySJNlkk03qrd90000zb968vPHGG2WvxcgVAAAAUDYr6ylXffv2Xer9kSNHLvHeOuuskx//+Mfp2bNnampq8ve//z3nnXde3n333Zx22mmZPn16kqRt27b1vrfw88L75STQAQAAAFiKnXfeOTvvvHPd5z59+qR58+a58sorc/TRR1elJoEOAAAAsMpbWgfOZ/GNb3wjl112WZ5//vm0a9cuSfLhhx9mnXXWqVszY8aMJKm7X04CHQAAAKBsakur7ilXS9K1a9ckn+yls/D3Cz83bdo0G220UdnfaVNkAAAAgBU0fPjwNG7cOFtuuWU22mijdOnSJXfdddcia3bcccc0a9as7O/XoQMAAACwFEcccUR69+6d7t27J/lkfOvGG2/Md77znboRqx//+Mc58cQT07lz5/Tu3TvDhw/P008/nauvvvpzqUmgAwAAAJTNqjhwtckmm+Tmm2/OO++8k9ra2nTp0iW/+MUvcsghh9StGTBgQGbPnp3BgwfnL3/5SzbZZJNceOGF2XbbbT+XmmpKpdVwuC1Jk2YbVrsEgLLq2m79apcAUFbPPn9jtUsAKKuma3dd9qJVwMEb/2e1S1isqyfeUu0SysoeOgAAAAAFY+QKAAAAKJvaVXLoauWjQwcAAACgYAQ6AAAAAAVj5AoAAAAom5KRq4rQoQMAAABQMAIdAAAAgIIxcgUAAACUTW21C1hN6NABAAAAKBiBDgAAAEDBGLkCAAAAyqbWKVcVoUMHAAAAoGAEOgAAAAAFY+QKAAAAKJuSkauK0KEDAAAAUDACHQAAAICCMXIFAAAAlE1ttQtYTejQAQAAACgYgQ4AAABAwRi5AgAAAMqmVHLKVSXo0AEAAAAoGIEOAAAAQMEYuQIAAADKpjZGripBhw4AAABAwQh0AAAAAArGyBUAAABQNrXVLmA1oUMHAAAAoGAEOgAAAAAFY+QKAAAAKJuSU64qQocOAAAAQMEIdAAAAAAKxsgVAAAAUDa1Rq4qQocOAAAAQMEIdAAAAAAKxsgVAAAAUDalkpGrStChAwAAAFAwAh0AAACAgjFyBQAAAJRNbbULWE3o0AEAAAAoGIEOAAAAQMEYuQIAAADKphSnXFWCDh0AAACAghHoAAAAABSMkSsAAACgbGqNXFWEDh0AAACAgtGhA2W25ZbdctqpP80Xtt06663XMbNmzc7zz7+UP/zxzxl2573VLg9gibbutWX2/e8B6b3TF7PhRhtk2gfT868nn8l5v704r73yepKkpqYm3zxwz3xtz92y5dbd0q59u0x6/a3ceds9GXLRVZn78dwq/xTA6mzWrNm57Nqheea5F/PMcy9mxocz85tf/CTf3HP3RdZeO/T2XHfLsEx66+2s2a5dvt73KznmyO+kZYs16ta8+fa72WP/wxb7rt+dcVL69/vq5/STACybQAfKbOPOndKmdatcdfVNeeutd9OyZYv85779c9utV+ToH/w8lw65ptolAizWkccemi9s3zN33X5fXnxufNbuuHYOPuKA3Pr3q/NfX/9uxr/wclq0XCNnDzo9Tz3+dK678pZMnTI1vbbbJsf+/PvZceft8p19j672jwGsxj6YPiN/vvzarL9ux3TfrGsef+rpxa7745+G5LJrhuZru/bJwQfsk5dfez3XDr09E16dmL+c+7+LrO+/+1ez847b1bvWa6sen8vPAKuCUsnIVSUIdKDMRtz194y46+/1rl30p8sz5rG7cvzx3xfoACutyy++Jj896peZN29+3bXht92TYaOuz/ePPTQ/++FpmTd3Xg7sf3ieevz//pJ049W35c3X38pxA4/Ol7+yfR55cEw1ygfIOmutmQduvyZrr9Uh455/Kf/9veMWWTPlvan56/W3Zq+v982Zp55Yd73LRhvmt+denAce/ke+2meHet/p0W3T7LXHbp97/QArwh46UAG1tbWZNOmttG/XttqlACzRU48/XS/MSZKJr7yR8S++kk27bZIkmTdvfr0wZ6F7h9+fJHXrAKqhWbNmWXutDktd869xz2f+ggX5Rt+v1Lv+jX67JElG3Ddqsd+bNXtO5s2bV55CAcpAhw58Tlq2bJEWLdZIu3Zts9eAr+Xre+yaG2+6vdplAaywtdfpkPEvvrL0NR3XTpJMfX9aBSoC+OwWhjJrNG9e7/oaa3zy+bkXJyzynYsvuzZ/uGhIampqsmX3zXLs9w/NTr2/+PkXCwXllKvKEOjA5+Sc3/0qR33/kCTJggULcuttI3LscadUuSqAFbP3/t/Iehusm/PPvmSp64485jv5cMbMPDhydIUqA/hsunTulCR56pnnsv0Xe9Zd/+fYZ5Mk7055v+5ao5qafHn7L6TvV76cdddZK2+89U7+ev2t+cGJp2XQ2b/KLl/evrLFA/yblS7QmTJlSubNm5cNNtggySebKd17772ZOHFiOnfunL59+6ZJk5WubFjEBYMG55Zb7sz6G6ybA/bbK40bN0qzZk2rXRbAcuu62cb51dkn5Z9jxubW64ctcd3Rx383O321d371szPz4YyZFawQYMVt2X2zbLNl9wy5+qZ0XGetbP+Fnnnltdfz699fmCZNmuTjuR/XrV1/vY6LbJK899f7Zu9vH5XfDxos0AGqaqVJRmbOnJnjjjsujzzySJKkb9+++f3vf5+jjjoqjz32WJo0aZL58+enR48eufrqq9OqVasqVwxL9+KLL+fFF19Oklx99dCMuPPa/O3WK7LjTgOqXBnAsq3dca385drz8+GMmTn28JNSW1u72HX9v7l7jj/5B7np6tty3RU3V7hKgM/m3N+ekhNPOzOn/vbcJEnjxo3ynQP/M0/865m89vqkpX63Xds2+Wb/3TPk6hvzzuQpWa/jOpUoGQqlZOSqIlaaTZEvvPDCPPvss/mf//mfnH/++Zk0aVKOPfbYvPHGG7ntttsybty4XH/99ZkyZUouv/zyapcLK+zmW+7Mdtttm27dNq12KQBL1bpNq1x6/QVp0651jjjwx5n87nuLXfflXXrndxeekQfufTinnXhmhasE+OzWXWftXHXxH3Ln9ZfmyovOychbr8pPf3RE3nl3SjbeaMNlfn/9dT8JcabrSgSqaKXp0Lnvvvvy4x//OAcccECSZMMNN8x+++2X3/zmN9liiy2SJL169coRRxyRW265Jcccc0w1y4UV1qLFGkk++bc6ACurZs2b5ZJrzk2Xrp1z2P4/zMsvvbrYddt84T9y0ZXn5Jmxz+e4752cBQsWVLhSgIbbeKMN6wKcl1+dmCnvT80+/Xdf5vfeeOvtJEmH9u0+1/oAlmalCXTefffddOvWre7z5ptvXu9/LrTFFlvkzTffrGhtsCLWWWetTPm3zfSSpEmTJjn44P0za9bsPPf8S1WqDGDpGjVqlPMGn5leX9omP/zOT/OvJ55Z7LpNN++SwdeenzdffztHfev4fDzn48WuAyiK2tra/OFPl6XFGs1z4Df7112f+sG0dFizfb217055L7cOuyfdNtsk66y99CPSYXVVWzJyVQkrTaDTunXrTJs2re5zkyZNsu6666ZFixb11n388cdp1GilmRSDRVz8p7PTtk2bPPTwP/Lmm+9kvfU65qCD9k2PLTbPiT87Ix99NKvaJQIs1sD/OT79vrFLRt71YNq1b5u99/9Gvfu3Dx2RVq1aZsiNF6Zt+za59KKr8tXd+9Rb8/prk5YYBAFUwrVDb8+HMz/K5Pc++RdsD4x+LO9O+WR09Fv77502rVvlzPP+nLlz56b75l0zf/6CDL/n/jzz/Ev531N+mvXX61j3rD/+6bK88ebb6f2lXum4doe8+fa7uelvIzJ7zpwMPO7oqvx8AAutNIHOZpttlrFjx2b33T9pcWzUqFFGjRq1yLoXX3wxnTt3rnR5sNxuvOn2HH7YQTnq+9/JWmutmQ8/nJl//vOZnPyL/82wYfdWuzyAJeqxVfckSd+vfyV9v/6VRe7fPnRE2ndolw06rZck+dlpP15kzS3X3yHQAarqiutuzlvvTK77fN+o0blv1OgkyYA9dkub1q3SY/NNc9WNt2XYPfenUU1Ntt6ye4acf2a9Y8yT5MvbfyE33nZnrr/5jsz4cGbatGmVL/bcKkcddlC27L5ZRX8ugE+rKZVWjl6oUaNGZfr06dl7772Xuu7HP/5xttlmmxx55JENel+TZsve7AygSLq2W7/aJQCU1bPP31jtEgDKqunaXatdQkXsvGHfapewWA+9ObLaJZTVStOhs8suuyzXukGDBn3OlQAAAACs3GxGAwAAAFAwK02HDgAAAFB8tVkpdnZZ5enQAQAAACgYgQ4AAABAwRi5AgAAAMrGyFVl6NABAAAAKBiBDgAAAEDBGLkCAAAAyqZUMnJVCTp0AAAAAApGoAMAAABQMEauAAAAgLJxylVl6NABAAAAKBiBDgAAAEDBGLkCAAAAyqZk5KoidOgAAAAAFIxABwAAAKBgjFwBAAAAZVMqGbmqBB06AAAAAAUj0AEAAAAoGCNXAAAAQNnUOuWqInToAAAAABSMQAcAAACgYIxcAQAAAGXjlKvK0KEDAAAAUDACHQAAAICCMXIFAAAAlI1TripDhw4AAABAwejQAQAAAFiKESNG5Pbbb8+zzz6bGTNmZOONN84hhxyS/fbbLzU1NUmSQw45JGPGjFnku8OHD8+mm25a9poEOgAAAEDZlFbBkasrrrgiG264YQYOHJg111wzjzzySE499dS88847OeaYY+rWfeELX8hJJ51U77udOnX6XGoS6AAAAAAsxcUXX5wOHTrUfd5xxx0zbdq0XH755fnhD3+YRo0+2dGmbdu26dWrV0VqsocOAAAAwFL8e5izUI8ePTJz5szMmjWrChXp0AEAAADKqLa06o1cLc6TTz6ZddddN61bt667NmbMmPTq1SsLFixIz549c9xxx2W77bb7XN4v0AEAAABWeX379l3q/ZEjRy73s5544okMHz683n452223XfbZZ5906dIlkydPzpAhQ/Ld7343V111VbbddtvPXPeS1JRKq0l09ilNmm1Y7RIAyqpru/WrXQJAWT37/I3VLgGgrJqu3bXaJVTEVuvuUO0SFmvdrVot9f7yBjrvvPNODjjggGy66aa57LLL6vbP+bRZs2ZlwIAB2XTTTTN48OAVrndZdOgAAAAAZbOynnK1Ih04SzJjxowceeSRad++fQYNGrTEMCdJWrZsmV122SV33313g9+7OAIdAAAAgGWYM2dOjjrqqHz44Ye54YYb0qZNm6rWI9ABAAAAWIr58+fn+OOPzyuvvJJrrrkm66677jK/M2vWrDzwwAPZeuutP5eaBDoAAABA2ayKp1ydccYZuf/++zNw4MDMnDkz//rXv+rubbnllnn66adz6aWXZvfdd8+GG26YyZMn5/LLL8+UKVNy/vnnfy41CXQAAAAAlmL06NFJkrPOOmuReyNHjsw666yTefPm5dxzz820adPSokWLbLvttjnjjDOyzTbbfC41CXQAAAAAluLvf//7MtcMGTKkApX8H4EOAAAAUDYr6ylXq5oln68FAAAAwEpJoAMAAABQMEauAAAAgLJZFU+5Whnp0AEAAAAoGIEOAAAAQMEYuQIAAADKxilXlaFDBwAAAKBgBDoAAAAABWPkCgAAACgbp1xVhg4dAAAAgIIR6AAAAAAUjJErAAAAoGycclUZOnQAAAAACkagAwAAAFAwRq4AAACAsimVaqtdwmpBhw4AAABAwQh0AAAAAArGyBUAAABQNrVOuaoIHToAAAAABSPQAQAAACgYI1cAAABA2ZRKRq4qQYcOAAAAQMEIdAAAAAAKxsgVAAAAUDZOuaoMHToAAAAABSPQAQAAACgYI1cAAABA2TjlqjJ06AAAAAAUjEAHAAAAoGCMXAEAAABlU2vkqiJ06AAAAAAUjEAHAAAAoGCMXAEAAABlU4qRq0rQoQMAAABQMAIdAAAAgIIxcgUAAACUTckpVxWhQwcAAACgYAQ6AAAAAAVj5AoAAAAom1qnXFWEDh0AAACAghHoAAAAABSMkSsAAACgbJxyVRk6dAAAAAAKRqADAAAAUDBGrgAAAICyqTVyVRE6dAAAAAAKRqADAAAAUDBGrgAAAICyccpVZejQAQAAACgYgQ4AAABAwRi5AgAAAMqmNkauKkGHDgAAAEDBCHQAAAAACsbIFQAAAFA2TrmqDB06AAAAAAUj0AEAAAAoGCNXAAAAQNnUGrmqCB06AAAAAAUj0AEAAAAoGCNXAAAAQNmUYuSqEnToAAAAABSMQAcAAACgYIxcAQAAAGXjlKvK0KEDAAAAUDACHQAAAICCMXIFAAAAlE3JyFVF6NABAAAAKBiBDgAAAEDBGLkCAAAAyqYUI1eVoEMHAAAAoGAEOgAAAAAFY+QKAAAAKBunXFWGDh0AAACAghHoAAAAABSMkSsAAACgbIxcVYYOHQAAAICCEegAAAAAFIyRKwAAAKBsDFxVhg4dAAAAgIIR6AAAAAAUTE3J9tMAAAAAhaJDBwAAAKBgBDoAAAAABSPQAQAAACgYgQ4AAABAwQh0AAAAAApGoAMAAABQMAIdAAAAgIIR6AAAAAAUjEAHAAAAoGAEOgAAAAAFI9ABAAAAKBiBDgAAAEDBCHQAAAAACqZJtQuAVdHEiRMzZMiQjB07NuPHj0/Xrl0zbNiwapcF8JmMGDEit99+e5599tnMmDEjG2+8cQ455JDst99+qampqXZ5ACts1KhRGTx4cCZMmJCZM2dm3XXXTb9+/XLMMcekTZs21S4PYLkIdOBzMH78+IwaNSo9e/ZMbW1tSqVStUsC+MyuuOKKbLjhhhk4cGDWXHPNPPLIIzn11FPzzjvv5Jhjjql2eQArbNq0adlmm21yyCGHpH379hk/fnwGDRqU8ePH57LLLqt2eQDLpabkb5pQdrW1tWnU6JOJxoEDB2bcuHE6dIDCmjp1ajp06FDv2qmnnprhw4fn8ccfr/vPO4Aiu/HGG3PqqafmwQcfzLrrrlvtcgCWyX8Dg8+Bv9wAq5JPhzlJ0qNHj8ycOTOzZs2qQkUA5de+ffskybx586pbCMByMnIFAKywJ598Muuuu25at25d7VIAPrMFCxZk/vz5mTBhQi666KLstttu6dSpU7XLAlguAh0AYIU88cQTGT58eE466aRqlwLQILvuumvefffdJMnOO++cP/zhD1WuCGD5mQsBAJbbO++8kxNOOCG9e/fOd77znWqXA9Agf/nLX3L99dfnN7/5TV555ZUcffTRWbBgQbXLAlguOnQAgOUyY8aMHHnkkWnfvn0GDRpkvzCg8LbYYoskybbbbputt946++yzT+699958/etfr3JlAMsm0AEAlmnOnDk56qij8uGHH+aGG25ImzZtql0SQFl17949TZs2zeuvv17tUgCWi0AHAFiq+fPn5/jjj88rr7ySa665xnG+wCpp7NixmTdvnk2RgcIQ6MDnYPbs2Rk1alSS5M0338zMmTNz1113JUm23377xR4BDLCyOuOMM3L//fdn4MCBmTlzZv71r3/V3dtyyy3TrFmz6hUH8Bkcc8wx2WqrrdK9e/esscYaeeGFFzJkyJB07949/fr1q3Z5AMulplQqlapdBKxqJk2alL59+y723l//+tf07t27whUBfHa77bZb3nzzzcXeGzlypH+bDRTOX/7ylwwfPjyvv/56SqVSNtxww+y+++454ogj0rp162qXB7BcBDoAAAAABeN4CgAAAICCEegAAAAAFIxABwAAAKBgBDoAAAAABSPQAQAAACgYgQ4AAABAwQh0AAAAAApGoAMArFR22223HHLIIdUuAwBgpSbQAYBVzPTp07PNNtuke/fuue222z7zcx577LEMGjQoM2bMKF9xAACUhUAHAFYxd9xxR+bOnZtOnTrl5ptv/szPGTNmTC688EKBDgDASkigAwCrmKFDh6Z379459NBD8/jjj+eNN96odkkAAJSZQAcAViHPPvtsnn/++ey7774ZMGBAmjRpkqFDhy6ybu7cuRk8eHD22Wef9OzZM1/84hfzn//5n7n66quTJAMHDsyFF16YJOnbt2+6d++e7t27Z9CgQXX3u3fvvtgaunfvnoEDB9a7ds011+Twww/PzjvvnK222ip9+vTJiSeemEmTJpXzxwcAWG00qXYBAED5DB06NC1btszXvva1tGzZMl/96ldz22235bjjjkujRp/8e5y5c+fmiCOOyJgxY9KnT5/svffead68eV566aXcc889Ofjgg3PggQdm5syZuffee3PyySdnzTXXTJIlhjjLctlll6VXr1455JBD0r59+7z00ksZOnRo/vGPf+SOO+6oez4AAMtHoAMAq4iPP/44w4YNyx577JGWLVsmSb75zW/m3nvvzUMPPZRddtklSXLllVdmzJgxOeqoo/KTn/yk3jNqa2uTJNtuu226d++ee++9N/369UunTp0aVNsdd9xRV9NCffv2zWGHHZahQ4fmyCOPbNDzAQBWN0auAGAVcc8992TGjBn55je/WXdtl112SYcOHeptjnzHHXekXbt2+dGPfrTIMxZ28ZTbwjCntrY2H374YaZOnZru3bunTZs2efrppz+XdwIArMp06ADAKmLo0KHp0KFD1ltvvUycOLHu+k477ZS77rorU6dOTYcOHTJx4sT06NEjzZs3r1htjz76aP70pz9l7Nix+fjjj+vdmz59esXqAABYVQh0AGAV8MYbb+Sxxx5LqVTKHnvssdg1t99+ew477LCyvK+mpmax1+fPn7/ItaeffjpHHHFEOnfunJ/+9Kfp1KlT1lhjjdTU1OSEE05IqVQqS00AAKsTgQ4ArAJuueWWlEql/OY3v0mbNm0WuX/eeefl5ptvzmGHHZYuXbrklVdeydy5c9OsWbMlPnNJoU2StGvXLkkybdq0tG/fvu764o5IHzZsWBYsWJDBgwdno402qrs+a9aszJgxY3l+PAAAPkWgAwAFV1tbm1tvvTXdunXLAQccsNg1EyZMyKBBg/L0009nr732yjnnnJM//elPOf744+utK5VKdUHOwn1vpk+fvsimyF26dEmSPPLII+nfv3/d9csvv3yRdzdu3HixNV1yySV1mzADALBiBDoAUHAPP/xw3n777ey///5LXPO1r30tgwYNytChQ3PKKafk/vvvz8UXX5xnnnkmffr0SbNmzTJhwoS8+uqrueKKK5IkPXv2TJL8/ve/z1577ZXmzZtn8803T7du3TJgwICce+65Oe200/LKK6+kffv2eeihh/LBBx8s8u5+/frliiuuyJFHHpkDDzwwTZs2zejRo/Piiy86rhwA4DNyyhUAFNzQoUOTJLvvvvsS13Tr1i1dunTJ8OHDU1tbm8suuyzHH3983nnnnfzxj3/Mueeem6effrreM774xS/mxBNPzOuvv55TTz01P/nJT3L33XcnSVq3bp2//OUv2WyzzXLJJZdk0KBB6dixYy699NJF3v3FL34xgwYNSsuWLXP++edn0KBBWWONNXL11VcvcpQ5AADLp6ZkJ0IAAACAQtGhAwAAAFAwAh0AAACAghHoAAAAABSMQAcAAACgYAQ6AAAAAAUj0AEAAAAoGIEOAAAAQMEIdAAAAAAKRqADAAAAUDACHQAAAICCEegAAAAAFIxABwAAAKBgBDoAAAAABfP/AKR9YtNCuZk3AAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 1500x1000 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "cm = confusion_matrix(y_test,y_pred)\n",
    "\n",
    "sns.heatmap(cm, annot=True, fmt='g', xticklabels=['1','2','3'], yticklabels=['1','2','3'])\n",
    "\n",
    "plt.ylabel('Prediction',fontsize=13)\n",
    "plt.xlabel('Actual',fontsize=13)\n",
    "plt.title('Confusion Matrix',fontsize=17)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
